package tip

import "ascale/pkg/ecode"

const ()

var codeMsgs = map[int]string{
	200:    "OK",
	1:      "App key invalid",
	2:      "AccessKey error",
	3:      "Sign check err",
	4:      "MethodNoPermission",
	101:    "NoLogin",
	102:    "UserDisabled",
	105:    "CaptchaErr",
	106:    "User is not active",
	109:    "Access restricted",
	108:    "AppDenied",
	110:    "MobileNoVerfiy",
	111:    "CsrfNotMatchErr",
	112:    "ServiceUpdate",
	304:    "NotModified",
	307:    "TemporaryRedirect",
	400:    "The API request is invalid.",
	401:    "Unauthorized",
	403:    "The requested operation is forbidden and cannot be completed.",
	404:    "Nothing found",
	405:    "Method is not allowed",
	409:    "Conflict",
	429:    "Request Too Fast",
	439:    "Do not repeat the operation",
	500:    "The request failed due to an internal error.",
	503:    "ServiceUnavailable",
	504:    "Deadline",
	509:    "LimitExceed",
	617:    "FileTooLarge",
	625:    "FailedTooManyTimes",
	628:    "PasswordTooLeak",
	629:    "Invalid password",
	632:    "TargetNumberLimit",
	643:    "TargetBlocked",
	652:    "UserDuplicate",
	658:    "AccessTokenExpires",
	662:    "PasswordHashExpires",
	700:    "The text is too long.",
	1200:   "Degrade",
	1201:   "RPCNoClient",
	1202:   "RPCNoAuth",
	20001:  "SMSTemplateIDNotExist",
	20002:  "SMSTemplateInvalid",
	20003:  "SMSTemplateExecuteFailed",
	21001:  "Failed to send email",
	22101:  "Missing Client id",
	22201:  "Verification code has expired.",
	22301:  "Wrong verification code :(",
	23001:  "User is already registered",
	23002:  "User is not registered. Please create a new account.",
	23003:  "Please fill out zipcode",
	23004:  "Your membership is canceled.",
	23005:  "We are not available in your location yet. Please email support@donefirst.com to subscribe to our waitlist.",
	23006:  "Email is already registered.",
	23101:  "Please input a valid state.",
	23102:  "Zipcode is incorrect.",
	23103:  "Zipcode and state does not match.",
	23104:  "You haven't had a provider yet.",
	23105:  "You've already reached the monthly maximum. Please email support@donefirst.com if you have urgent issue.",
	23106:  "We cannot find this email in our database",
	23107:  "Phone is already registered.",
	23108:  "The clinicians currently cannot see patients who are under 18 years old.",
	23109:  "please cancel your membership before you do this.",
	23110:  "The phone has not changed.",
	23111:  "The email has not changed.",
	23112:  "Doctors cannot modify it.",
	23113:  "Not in service area.",
	23114:  "Verifiable provider not found.",
	23115:  "Verifiable provider license not found.",
	23116:  "Verifiable provider DEA not found.",
	23117:  "Patient's state does not support pull PDMP. Please email support@donefirst.com to upload PDMP.",
	23118:  "This email is already verified. Please log in with your phone number.",
	23119:  "Please verify your identity first to access PDMP information.",
	23201:  "Timezone error",
	23202:  "You've already had a ongoing appointment.",
	23203:  "Appointment time is no longer available.",
	23204:  "Clients are not allowed to cancel this close to the time of the appointment.",
	23205:  "Sorry, reschedule is not allowed since your appointment will start soon.",
	23206:  "Appointment has been already set diagnosed.",
	23207:  "Appointment's status does meet requirements",
	23210:  "no initial appointment",
	23211:  "Must have a diagnosed initial appointment first.",
	23212:  "Must book appointment with assigned provider",
	23213:  "Must have a follow up appointment first.",
	23214:  "please submit a clinician note before submitting the discharge request.",
	23215:  "Patient already has a discharge note",
	23216:  "You've already had a ongoing appointment request.",
	23217:  "Patient already has a unconfirmed appointment request.",
	23218:  "Note type error, please reselect the note type.",
	23219:  "Sorry, this patient has been accepted by another provider.",
	23220:  "Sorry, your appointment request preferred times not available, please select again.",
	23221:  "Sorry, your appointment time is not within the therapy membership period, please select again.",
	23301:  "Please add a payment method.",
	23302:  "Charge failed",
	23303:  "Current payment status not allowed to refund.",
	23305:  "Refund amount incorrect.",
	23306:  "Only allowed to participate once during the event period",
	23307:  "Charge failed,please update payment method.",
	23308:  "Repeated payment method.",
	23309:  "The payment will auto refund.",
	23401:  "Invalid gcloud account key json file.",
	23402:  "Invalid upload token type",
	23501:  "Please input a valid address.",
	23502:  "Please upload your photo ID",
	23503:  "Please input a valid emergency contact",
	23505:  "Patient need finish intake form",
	23506:  "Patient need finish your legal name form",
	23600:  "This appointment can't be scheduled due to acuity's problem.",
	23601:  "Clients are not allowed to cancel this close to the time of the appointment.",
	23602:  "Clients are not allowed to cancel.",
	23603:  "Clients are not allowed to reschedule.",
	23605:  "Clients are not allowed to reschedule this close to the time of the appointment.",
	23606:  "Class series may not be rescheduled.",
	23607:  "Canceled appointments may not be rescheduled.",
	23608:  "The calendar does not exist or not belong one appointmentType.",
	23609:  "The parameter \"datetime\" is required.",
	23610:  "Invalid timezone.",
	23611:  "The datetime is invalid.",
	23612:  "The time is not far enough in advance.",
	23613:  "The time is too far in advance.",
	23614:  "The time is not an available time slot.",
	23615:  "Attribute \"firstName\" is required.",
	23616:  "Attribute \"lastName\" is required.",
	23617:  "Attribute \"email\" is required.",
	23618:  "Invalid \"email\" attribute value.",
	23619:  "The field \"1\" does not exist on this appointment.",
	23620:  "The field \"4\" is required.",
	23621:  "The parameter \"appointmentTypeID\" is required",
	23622:  "The appointment type does not exist.",
	23627:  "We could not find an available calendar.",
	23631:  "The certificate \"NOCODENOPROBLEM\" is invalid.",
	23632:  "The certificate \"EXPIRED\" is expired.",
	23633:  "The certificate \"8013DA6F\" has no remaining uses for appointment type.",
	23634:  "The certificate \"E5E5325C\" is invalid for appointment type.",
	23635:  "The time is blocked.",
	23701:  "The patient is not assigned to you",
	23702:  "The appointment is not paid yet. ",
	23703:  "The appointment's status is not allowed to revert because it's New or Confirmed.",
	23704:  "The appointment was canceled",
	23705:  "The appointment was marked as a no-show",
	23706:  "The appointment was marked as no-diagnosis",
	23801:  "It's too early to request a refill.",
	23802:  "You already requested a refill.",
	23803:  "No treatment plan yet",
	23804:  "The last three month renewal time span is not finished yet",
	23805:  "Refill request is already note added",
	23806:  "Refill request is already processed and cannot be audited for dispute.",
	23807:  "Appointment needed for continued treatment.",
	23901:  "We are experiencing high volume. Please try again later.",
	24001:  "The email address provided for the creation of a deferred account already has an account associated with it.",
	24002:  "The country of the business address provided does not match the country of the account.",
	24003:  "The account ID provided as a value for the Stripe-Account header is invalid. Check that your requests are specifying a valid account ID.",
	24004:  "The bank account number provided is invalid.",
	24005:  "This method for creating Alipay payments is not supported anymore.",
	24006:  "The specified amount is greater than the maximum amount allowed.",
	24007:  "The specified amount is less than the minimum amount allowed.",
	24008:  "The API key provided has expired.",
	24009:  "The payment requires authentication to proceed.",
	24010:  "The transfer or payout could not be completed because the associated account does not have a sufficient balance available.",
	24011:  "The bank account provided can not be used to charge, either because it is not verified yet or it is not supported.",
	24012:  "The bank account provided already exists on the specified Customer object.",
	24013:  "The bank account provided cannot be used for payouts.",
	24014:  "Your Connect platform is attempting to share an unverified bank account with a connected account.",
	24015:  "The bank account cannot be verified, either because the microdeposit amounts provided do not match the actual amounts, or because verification has failed too many times.",
	24016:  "This method for creating Bitcoin payments is not supported anymore.",
	24017:  "This card has been declined too many times. You can try to charge this card again after 24 hours.",
	24018:  "The card has been declined.",
	24019:  "The charge you’re attempting to capture has already been captured.",
	24020:  "The charge you’re attempting to refund has already been refunded.",
	24021:  "The charge you’re attempting to refund has been charged back.",
	24022:  "This charge would cause you to exceed your rolling-window processing limit for this source type.",
	24023:  "The charge cannot be captured as the authorization has expired.",
	24024:  "One or more provided parameters was not allowed for the given operation on the Charge.",
	24025:  "The clearing code provided is not supported.",
	24026:  "The country code provided was invalid.",
	24027:  "Your platform attempted to create a custom account in a country that is not yet supported.",
	24028:  "The coupon provided for a subscription or order has expired.",
	24029:  "The maximum number of PaymentMethods for this Customer has been reached.",
	24030:  "The maximum number of subscriptions for a customer has been reached.",
	24031:  "The email address is invalid (e.g., not properly formatted).",
	24032:  "The card has expired. Check the expiration date or use a different card.",
	24033:  "The idempotency key provided is currently being used in another request.",
	24034:  "The card’s address is incorrect.",
	24035:  "The card’s security code is incorrect.",
	24036:  "The card number is incorrect. Check the card’s number or use a different card.",
	24037:  "The card’s ZIP code is incorrect. Check the card’s ZIP code or use a different card.",
	24038:  "This card is not eligible for Instant Payouts.  Try a debit card from a supported bank.",
	24039:  "Intent is not the state that is rquired to perform the operation.",
	24040:  "Intent does not have verification method specified in its PaymentMethodOptions object.",
	24041:  "The card provided as an external account is not supported for payouts.",
	24042:  "This value provided to the field contains characters that are unsupported by the field.",
	24043:  "The specified amount is invalid.",
	24044:  "The card’s security code is invalid. Check the card’s security code or use a different card.",
	24045:  "The card’s expiration month is incorrect. Check the expiration date or use a different card.",
	24046:  "The card’s expiration year is incorrect. Check the expiration date or use a different card.",
	24047:  "The card number is invalid. Check the card details or use a different card.",
	24048:  "The source cannot be used because it is not in the correct state",
	24049:  "An invoice cannot be generated for the specified customer as there are no pending invoice items.",
	24050:  "An invoice cannot be finalized because there are no payment method types available to process the payment.",
	24051:  "An invoice cannot be generated for the specified subscription as there are no pending invoice items.",
	24052:  "The specified invoice can no longer be edited. Instead, consider creating additional invoice items that will be applied to the next invoice.",
	24053:  "This payment requires additional user action before it can be completed successfully.",
	24054:  "There is no upcoming invoice on the specified customer to preview.",
	24055:  "Test and live mode API keys, requests, and objects are only available within the mode they are in.",
	24056:  "This object cannot be accessed right now because another API request or Stripe process is currently accessing it. If you see this error intermittently, retry the request",
	24057:  "Both a customer and source ID have been provided, but the source has not been saved to the customer.",
	24058:  "Transfers and payouts on behalf of a Standard connected account are not allowed.",
	24059:  "The order could not be created. Check the order details and then try again.",
	24060:  "The order could not be processed as it is missing required information. Check the information provided and try again.",
	24061:  "The order cannot be updated because the status provided is either invalid or does not follow the order lifecycle.",
	24062:  "The request timed out. Try again later.",
	24063:  "The SKU is out of stock. If more stock is available, update the SKU’s inventory quantity and try again.",
	24064:  "One or more required values were not provided.",
	24065:  "One or more of the parameters requires an integer, but the values provided were a different type.",
	24066:  "One or more values provided only included whitespace.",
	24067:  "One or more required string values is empty.",
	24068:  "One or more required values are missing.",
	24069:  "The request contains one or more unexpected parameters.",
	24070:  "Two or more mutually exclusive parameters were provided.",
	24071:  "The provided payment method requires customer actions to complete, but error_on_requires_action was set. I",
	24072:  "The provided payment method has failed authentication. Provide a new payment method to attempt to fulfill this PaymentIntent again.",
	24073:  "The PaymentIntent expected a payment method with different properties than what was provided.",
	24074:  "One or more provided parameters was not allowed for the given operation on the PaymentIntent.",
	24075:  "The latest payment attempt for the PaymentIntent has failed.",
	24076:  "The PaymentIntent’s state was incompatible with the operation you were trying to perform.",
	24077:  "Invalid parameter was provided in the payment method object.",
	24078:  "The payment was declined by the issuer or customer.",
	24079:  "The payment method failed due to a timeout.",
	24080:  "The operation cannot be performed as the payment method used has not been activated.",
	24081:  "The provided payment method’s state was incompatible with the operation you were trying to perform.",
	24082:  "Payouts have been disabled on the connected account.",
	24083:  "The API key provided by your Connect platform has expired.",
	24084:  "The ZIP code provided was incorrect.",
	24085:  "An error occurred while processing the card. Try again later or with a different payment method.",
	24086:  "The product this SKU belongs to is no longer available for purchase.",
	24087:  "Too many requests hit the API too quickly. We recommend an exponential backoff of your requests.",
	24088:  "A resource with a user-specified ID (e.g., plan or coupon) already exists.",
	24089:  "The ID provided is not valid. Either the resource does not exist, or an ID for a different resource has been provided.",
	24090:  "The bank routing number provided is invalid.",
	24091:  "The API key provided is a publishable key, but a secret key is required.",
	24092:  "Your account does not support SEPA payments.",
	24093:  "The latest setup attempt for the SetupIntent has failed.",
	24094:  "The provided payment method has failed authentication.",
	24095:  "One or more provided parameters was not allowed for the given operation on the SetupIntent.",
	24096:  "The SetupIntent’s state was incompatible with the operation you were trying to perform.",
	24097:  "Shipping calculation failed as the information provided was either incorrect or could not be verified.",
	24098:  "The SKU is inactive and no longer available for purchase.",
	24099:  "Occurs when providing the legal_entity information for a U.S. custom account, if the provided state is not supported.",
	24100:  "The tax ID number provided is invalid (e.g., missing digits).",
	24101:  "Tax calculation for the order failed.",
	24102:  "Terminal is currently only available in some countries.",
	24103:  "Your account has not been activated and can only make test charges.",
	24104:  "Your integration is using an older version of TLS that is unsupported. You must be using TLS 1.2 or above.",
	24105:  "The token provided has already been used. You must create a new token before you can retry this request.",
	24106:  "The token provided is currently being used in another request. This occurs if your integration is making duplicate requests simultaneously.",
	24107:  "The requested transfer cannot be created.",
	24108:  "The order could not be created. Check the order details and then try again.",
	24109:  "The URL provided is invalid.",
	24110:  "The card was declined as the transaction requires authentication.",
	24111:  "The payment can’t be authorized.",
	24112:  "The card was declined for an unknown reason.",
	24113:  "The card does not support this type of purchase.",
	24114:  "The customer has exceeded the balance or credit limit available on their card.",
	24115:  "The card does not support the specified currency.",
	24116:  "The card was declined for an unknown reason.",
	24117:  "The card was declined for an unknown reason.",
	24118:  "A transaction with identical amount and credit card information was submitted very recently.",
	24119:  "The card has expired.",
	24120:  "The payment was declined because Stripe suspects that it’s fraudulent.",
	24121:  "The card was declined for an unknown reason or possibly triggered by a blocked payment rule.",
	24122:  "The card number is incorrect.",
	24123:  "The CVC number is incorrect.",
	24124:  "The PIN entered is incorrect. This decline code only applies to payments made with a card reader.",
	24125:  "The postal code is incorrect.",
	24126:  "The card has insufficient funds to complete the purchase.",
	24127:  "The card, or account the card is connected to, is invalid.",
	24128:  "The payment amount is invalid, or exceeds the amount that’s allowed.",
	24129:  "The CVC number is incorrect.",
	24130:  "The expiration month is invalid.",
	24131:  "The expiration year is invalid.",
	24132:  "The card number is incorrect.",
	24133:  "The PIN entered is incorrect. This decline code only applies to payments made with a card reader.",
	24134:  "The card issuer couldn’t be reached, so the payment couldn’t be authorized.",
	24135:  "The payment was declined because the card is reported lost.",
	24136:  "The payment was declined because it matches a value on the Stripe user’s block list.",
	24137:  "The card, or account the card is connected to, is invalid.",
	24138:  "The card was declined for an unknown reason.",
	24139:  "The payment isn’t permitted.",
	24140:  "The card was declined because it requires a PIN.",
	24141:  "The card was declined as it requires a PIN.",
	24142:  "The customer can’t use this card to make this payment (it’s possible it was reported lost or stolen).",
	24143:  "The allowable number of PIN tries was exceeded.",
	24144:  "An error occurred while processing the card.",
	24145:  "The payment couldn’t be processed by the issuer for an unknown reason.",
	24146:  "The customer can’t use this card to make this payment (it’s possible it was reported lost or stolen).",
	24147:  "The card was declined for an unknown reason.",
	24148:  "The card was declined for an unknown reason.",
	24149:  "The card was declined for an unknown reason.",
	24150:  "The card was declined for an unknown reason.",
	24151:  "The payment was declined because the card is reported stolen.",
	24152:  "The card was declined for an unknown reason.",
	24153:  "A Stripe test card number was used.",
	24154:  "The card was declined for an unknown reason.",
	24155:  "The card was declined for an unknown reason.",
	24156:  "The customer has exceeded the balance or credit limit available on their card.",
	24440:  "The interval between the two requests is too close.",
	24510:  "Please set up your account first.",
	24511:  "The amount must be greater than 0.",
	25001:  "Doctor have active patients, please transfer them first.",
	25002:  "You can't transfer patients from one doctor to himself",
	25003:  "This clinician does not support the patient's state.",
	25004:  "You need to transfer patient's appointments",
	25005:  "The Appointment Type ID is used by another clinician",
	25006:  "The Follow Up Appointment Type ID is used by another clinician",
	25007:  "The External Calendar ID is used by another clinician",
	25008:  "Please cancel all appointments for this patient",
	25009:  "Please fill doctor's in person visit info first.",
	25010:  "Doctor have active memberships patient, please transfer them first.",
	25011:  "transfer action not empty.",
	25012:  "The patient has not completed the initial appointment. Please schedule an initial appointment for the patient.",
	25101:  "This prescription can not to be cancel now.",
	26001:  "You need sync patient info to ayva first",
	26100:  "Clinician's address is required.",
	26101:  "Clinician's navigation instruction is required.",
	26102:  "Clinician's in-person appointment type id is required.",
	27100:  "This medicine already exists.",
	27101:  "This medicine pill time must greater than 0.",
	27102:  "This medicine pill left is not enough.",
	28100:  "This pharmacy blacklist already exists.",
	28110:  "The pharmacy you have chosen is not available for your prescription, please change a pharmacy.",
	30001:  "According to our records, you were discharged from your treatment.",
	30002:  "Your reactivation request already sent.",
	30003:  "Failed to resume your membership.",
	30004:  "Already has reactive request",
	30005:  "There is no suitable doctor",
	30006:  "The patient has active membership",
	30007:  "You have already chosen this therapy plan.",
	30008:  "The patient has pending therapy plan.",
	30009:  "The patient does not have an active therapy subscription, please contact care team for support",
	30010:  "The weeks too large",
	30011:  "Only active members can extend membership by week",
	30012:  "Target member has extended",
	30013:  "No membership record found for next month,please try again later",
	30014:  "Annual membership does not allow this operation",
	60000:  "Something's wrong. Please try again.",
	60001:  "Wrong code. Please try again.",
	60200:  "Please enter a valid phone number.",
	60202:  "Too many failed attempts. Please try again after 10 minutes.",
	60203:  "Too many failed attempts. Please try again after 10 minutes.",
	60205:  "Please enter a cellphone number",
	60401:  "You need sync patient info to rxnt first",
	60402:  "Your rxnt username or password error.",
	60403:  "rxnt doctor not found.",
	60404:  "You do not have an RXNT account to prescribe to Texas patients, please contact your PRM",
	90100:  "Tags Name exist.",
	90200:  "Tags Still Used.",
	91100:  "you already obtained this gift or not match obtain condition.",
	114111: "Reschedule Time Must be limited to 5 days.",
	114112: "Your additional time conflict with regular schedule.",
	114113: "Appointment Status Must Be Confirm.",
	114114: "None Available Time Slot For Patient",
	114115: "Your already accept.",
	116000: "Failed to sync patient info to apero",
	116001: "Failed to get patient info from apero",
	116002: "Failed to get provider info from apero",
	116003: "Failed to sync provider info to apero",
	116004: "Failed to sync facility info to apero",
	116005: "Failed to sync appointment info to apero",
	116006: "Failed to get facility info from apero",
	116007: "Failed to get insurance info from apero",
	116008: "Failed to sync invoice info to apero",
	116009: "Apero Invoice already exists",
	116010: "Patient homebase not found",
	116011: "Doctor location not found",
	116012: "Apero appointment id not found",
	116013: "User address not found",

	117000: "Refresh zoho token is failed.",
	120404: "code not found.",
	120504: "code has expired.",
	120800: "You've already sent an email to this address today",
	120801: "Exceed year limit",
	120802: "Not active membership",
	140000: "Incorrect time interval.",

	130000: "Get Candid access token failed",
	130001: "Post Candid Encounter Failed",
	118000: "Paypal create authorization unexpected, please try again later.",
	118001: "Paypal Agreement Inactive, please update your method.",
	118002: "The interval between the two requests is too close.",
	118003: "Refund failed.",
}

func Init() {
	ecode.Register(codeMsgs)
}
