global:
  image: gcr.io/ascale-439911/ascale:1.0.3
  pullPolicy: IfNotPresent
  platform: donefirst
  type: api
  name: ascale 
  gitVersion: c91b2e62e7957cc8b8dcc5b78c2b0f7fc544c663
  googleCredential: false
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: letsencrypt-prod
  paths:
    - /
  hosts:
    - api-uat.liyinjia.com
  tls:
    - secretName: uat-api-tls
      hosts:
        - api-uat.liyinjia.com
server:
  serviceAccountName: done-sql
  replicas: 1
  bootstrapExpect: 1
  exEnv:
    CI: 1
    ENV: "production"
    GCLOUD_PROJECT: "ascale-439911"
worker:
  enabled: false
  replicas: 1
  image: gcr.io/ascale-439911/ascale-worker:1.0.3
  name: ascale-worker
  type: worker
  exEnv:
    CI: 1
    ENV: "production"
    GCLOUD_PROJECT: "ascale-439911"

# GKE use UTC as default CronJob timezone,
# if you want cronjob to be execute at specific time, convert time to UTC timezone
cronjob:
  jobs:
    - name: "cron-send-messages"
      job: "SendMessages"
      schedule: "*/2 * * * *"
