apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.global.name }}-worker"
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: "{{ .Values.global.name }}-worker"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    platform: {{ .Values.global.platform }}
    type: {{ .Values.global.type }}
    gitVersion: {{ .Values.global.gitVersion }}
spec:
  type: LoadBalancer
  # We want the servers to become available even if they're not ready
  # since this DNS is also used for join operations.
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: "{{ .Values.global.name }}-worker"
    release: "{{ .Release.Name }}"
    component: server





